const List<String> indianCities = [
  'Mumbai, Maharashtra',
  'Delhi, Delhi',
  'Bengaluru, Karnataka',
  'Hyderabad, Telangana',
  'Ahmedabad, Gujarat',
  'Chennai, Tamil Nadu',
  'Kolkata, West Bengal',
  'Surat, Gujarat',
  'Pune, Maharashtra',
  'Jaipur, Rajasthan',
  'Lucknow, Uttar Pradesh',
  'Kanpur, Uttar Pradesh',
  'Nagpur, Maharashtra',
  'Indore, Madhya Pradesh',
  'Thane, Maharashtra',
  'Bhopal, Madhya Pradesh',
  'Visakhapatnam, Andhra Pradesh',
  'Pimpri-Chinchwad, Maharashtra',
  'Patna, Bihar',
  'Vadodara, Gujarat',
  'Ghaziabad, Uttar Pradesh',
  'Ludhiana, Punjab',
  'Agra, Uttar Pradesh',
  'Nashik, Maharashtra',
  'Ranchi, Jharkhand',
  'Faridabad, Haryana',
  'Meerut, Uttar Pradesh',
  'Rajkot, Gujarat',
  'Kalyan-Dombivli, Maharashtra',
  'Vasai-Virar, Maharashtra',
  'Varanasi, Uttar Pradesh',
  'Srinagar, Jammu and Kashmir',
  'Aurangabad, Maharashtra',
  'Dhanbad, Jharkhand',
  'Amritsar, Punjab',
  'Navi Mumbai, Maharashtra',
  'Allahabad, Uttar Pradesh',
  'Howrah, West Bengal',
  'Gwalior, Madhya Pradesh',
  'Jabalpur, Madhya Pradesh',
  'Coimbatore, Tamil Nadu',
  'Vijayawada, Andhra Pradesh',
  'Jodhpur, Rajasthan',
  'Madurai, Tamil Nadu',
  'Raipur, Chhattisgarh',
  'Kota, Rajasthan',
  'Guwahati, Assam',
  'Chandigarh, Chandigarh',
  'Solapur, Maharashtra',
  'Hubli-Dharwad, Karnataka',
  'Bareilly, Uttar Pradesh',
  'Moradabad, Uttar Pradesh',
  'Mysore, Karnataka',
  'Gurgaon, Haryana',
  'Aligarh, Uttar Pradesh',
  'Jalandhar, Punjab',
  'Tiruchirappalli, Tamil Nadu',
  'Bhubaneswar, Odisha',
  'Salem, Tamil Nadu',
  'Mira-Bhayandar, Maharashtra',
  'Thiruvananthapuram, Kerala',
  'Bhiwandi, Maharashtra',
  'Saharanpur, Uttar Pradesh',
  'Gorakhpur, Uttar Pradesh',
  'Guntur, Andhra Pradesh',
  'Bikaner, Rajasthan',
  'Amravati, Maharashtra',
  'Noida, Uttar Pradesh',
  'Jamshedpur, Jharkhand',
  'Bhilai, Chhattisgarh',
  'Cuttack, Odisha',
  'Firozabad, Uttar Pradesh',
  'Kochi, Kerala',
  'Nellore, Andhra Pradesh',
  'Bhavnagar, Gujarat',
  'Dehradun, Uttarakhand',
  'Durgapur, West Bengal',
  'Asansol, West Bengal',
  'Rourkela, Odisha',
  'Nanded, Maharashtra',
  'Kolhapur, Maharashtra',
  'Ajmer, Rajasthan',
  'Akola, Maharashtra',
  'Gulbarga, Karnataka',
  'Jamnagar, Gujarat',
  'Ujjain, Madhya Pradesh',
  'Loni, Uttar Pradesh',
  'Siliguri, West Bengal',
  'Jhansi, Uttar Pradesh',
  'Ulhasnagar, Maharashtra',
  'Jammu, Jammu and Kashmir',
  'Sangli-Miraj & Kupwad, Maharashtra',
  'Mangalore, Karnataka',
  'Erode, Tamil Nadu',
  'Belgaum, Karnataka',
  'Ambattur, Tamil Nadu',
  'Tirunelveli, Tamil Nadu',
  'Malegaon, Maharashtra',
  'Gaya, Bihar',
  'Jalgaon, Maharashtra',
  'Udaipur, Rajasthan',
  'Maheshtala, West Bengal',
  'Davanagere, Karnataka',
  'Kozhikode, Kerala',
  'Kurnool, Andhra Pradesh',
  'Rajpur Sonarpur, West Bengal',
  'Rajahmundry, Andhra Pradesh',
  'Bokaro, Jharkhand',
  'South Dumdum, West Bengal',
  'Bellary, Karnataka',
  'Patiala, Punjab',
  'Gopalpur, West Bengal',
  'Agartala, Tripura',
  'Bhagalpur, Bihar',
  'Muzaffarnagar, Uttar Pradesh',
  'Bhatpara, West Bengal',
  'Panihati, West Bengal',
  'Latur, Maharashtra',
  'Dhule, Maharashtra',
  'Tirupati, Andhra Pradesh',
  'Rohtak, Haryana',
  'Korba, Chhattisgarh',
  'Bhilwara, Rajasthan',
  'Berhampur, Odisha',
  'Muzaffarpur, Bihar',
  'Ahmednagar, Maharashtra',
  'Mathura, Uttar Pradesh',
  'Kollam, Kerala',
  'Avadi, Tamil Nadu',
  'Kadapa, Andhra Pradesh',
  'Kamarhati, West Bengal',
  'Sambalpur, Odisha',
  'Bilaspur, Chhattisgarh',
  'Shahjahanpur, Uttar Pradesh',
  'Satara, Maharashtra',
  'Bijapur, Karnataka',
  'Rampur, Uttar Pradesh',
  'Shimoga, Karnataka',
  'Chandrapur, Maharashtra',
  'Junagadh, Gujarat',
  'Thrissur, Kerala',
  'Alwar, Rajasthan',
  'Bardhaman, West Bengal',
  'Kulti, West Bengal',
  'Kakinada, Andhra Pradesh',
  'Nizamabad, Telangana',
  'Parbhani, Maharashtra',
  'Tumkur, Karnataka',
  'Khammam, Telangana',
  'Ozhukarai, Puducherry',
  'Bihar Sharif, Bihar',
  'Panipat, Haryana',
  'Darbhanga, Bihar',
  'Bally, West Bengal',
  'Aizawl, Mizoram',
  'Dewas, Madhya Pradesh',
  'Ichalkaranji, Maharashtra',
  'Karnal, Haryana',
  'Bathinda, Punjab',
  'Jalna, Maharashtra',
  'Eluru, Andhra Pradesh',
  'Karawal Nagar, Delhi',
  'Barasat, West Bengal',
  'Kirari Suleman Nagar, Delhi',
  'Purnia, Bihar',
  'Satna, Madhya Pradesh',
  'Mau, Uttar Pradesh',
  'Sonipat, Haryana',
  'Farrukhabad, Uttar Pradesh',
  'Sagar, Madhya Pradesh',
  'Rourkela, Odisha',
  'Durg, Chhattisgarh',
  'Imphal, Manipur',
  'Ratlam, Madhya Pradesh',
  'Hapur, Uttar Pradesh',
  'Anantapur, Andhra Pradesh',
  'Arrah, Bihar',
  'Karimnagar, Telangana',
  'Parbhani, Maharashtra',
  'Etawah, Uttar Pradesh',
  'Ambernath, Maharashtra',
  'North Dumdum, West Bengal',
  'Bharatpur, Rajasthan',
  'Begusarai, Bihar',
  'New Delhi, Delhi',
  'Gandhidham, Gujarat',
  'Baranagar, West Bengal',
  'Tiruvottiyur, Tamil Nadu',
  'Puducherry, Puducherry',
  'Sikar, Rajasthan',
  'Thoothukudi, Tamil Nadu',
  'Rewa, Madhya Pradesh',
  'Mirzapur, Uttar Pradesh',
  'Raichur, Karnataka',
  'Pali, Rajasthan',
  'Ramagundam, Telangana',
  'Haridwar, Uttarakhand',
  'Vijayanagaram, Andhra Pradesh',
  'Katihar, Bihar',
  'Nagercoil, Tamil Nadu',
  'Sri Ganganagar, Rajasthan',
  'Karawal Nagar, Delhi',
  'Mango, Jharkhand',
  'Thanjavur, Tamil Nadu',
  'Bulandshahr, Uttar Pradesh',
  'Uluberia, West Bengal',
  'Murwara, Madhya Pradesh',
  'Sambhal, Uttar Pradesh',
  'Singrauli, Madhya Pradesh',
  'Nadiad, Gujarat',
  'Secunderabad, Telangana',
  'Naihati, West Bengal',
  'Yamunanagar, Haryana',
  'Bidhannagar, West Bengal',
  'Pallavaram, Tamil Nadu',
  'Bidar, Karnataka',
  'Munger, Bihar',
  'Panchkula, Haryana',
  'Burhanpur, Madhya Pradesh',
  'Raurkela Industrial Township, Odisha',
  'Kharagpur, West Bengal',
  'Dindigul, Tamil Nadu',
  'Gandhinagar, Gujarat',
  'Hospet, Karnataka',
  'Nangloi Jat, Delhi',
  'English Bazar, West Bengal',
  'Ongole, Andhra Pradesh',
  'Deoghar, Jharkhand',
  'Chapra, Bihar',
  'Haldia, West Bengal',
  'Khandwa, Madhya Pradesh',
  'Nandyal, Andhra Pradesh',
  'Chittoor, Andhra Pradesh',
  'Morena, Madhya Pradesh',
  'Amroha, Uttar Pradesh',
  'Anand, Gujarat',
  'Bhind, Madhya Pradesh',
  'Bhalswa Jahangir Pur, Delhi',
  'Madhyamgram, West Bengal',
  'Bhiwani, Haryana',
  'Navi Mumbai Panvel Raigad, Maharashtra',
  'Baharampur, West Bengal',
  'Ambala, Haryana',
  'Morvi, Gujarat',
  'Fatehpur, Uttar Pradesh',
  'Rae Bareli, Uttar Pradesh',
  'Khora, Uttar Pradesh',
  'Bhusawal, Maharashtra',
  'Orai, Uttar Pradesh',
  'Bahraich, Uttar Pradesh',
  'Vellore, Tamil Nadu',
  'Mahesana, Gujarat',
  'Raiganj, West Bengal',
  'Sirsa, Haryana',
  'Danapur, Bihar',
  'Serampore, West Bengal',
  'Sultan Pur Majra, Delhi',
  'Guna, Madhya Pradesh',
  'Jaunpur, Uttar Pradesh',
  'Panvel, Maharashtra',
  'Shivpuri, Madhya Pradesh',
  'Surendranagar Dudhrej, Gujarat',
  'Unnao, Uttar Pradesh',
  'Hugli and Chinsurah, West Bengal',
  'Alappuzha, Kerala',
  'Kottayam, Kerala',
  'Machilipatnam, Andhra Pradesh',
  'Shimla, Himachal Pradesh',
  'Barmer, Rajasthan',
  'Balotra, Rajasthan',
  'Jalore, Rajasthan',
  'Sirohi, Rajasthan',
  'Jaisalmer, Rajasthan'
];
